CFLAGS = -c
CWARNINGS = -Wall

ejercicio1010: ejercicio1010.o
	$(CC) ejercicio1010.o -o ejercicio1010

ejercicio1010.o: ejercicio1010.c
	$(CC) $(CFLAGS) $(CWARNINGS) ejercicio1010.c

clean:
	$(RM) *.o ejercicio1010 core
